const dummyNames = [
    "Glutenfria kanelbullar",
    "Kr\u00e4mig pastasallad med kyckling",
    "Tortellinigrat\u00e4ng med svamp och franska \u00f6rter",
    "Pasta alle vongole",
    "Kasslergryta med zucchini, tomat och basilika",
    "Morotsbiffar med fetaost och soltorkade tomater",
    "Pasta pomodoro med basilika och vitost",
    "Pannkaksmuffins",
    "Ramen med biff, brynt sm\u00f6r och svart vitl\u00f6k",
    "Dutch baby pancake",
    "Kr\u00e4mig \u00e4ggr\u00f6ra med cheddarost",
    "\u00c4ggr\u00f6ra med cr\u00e8me fraiche",
    "Stuvade makaroner utan mj\u00f6l",
    "Risonipaella med saffran",
    "Cheese tea - F\u00e4skostte",
    "Chokladmuffins",
    "Beef Wellington",
    "Japanese cotton cheesecake - Japansk cheesecake",
    "Citronkladdkaka",
    "R\u00e5biff med kapriskr\u00e4m",
    "Mandelkubb",
    "Semmelkladdkaka",
    "Palt",
    "L\u00f6ks\u00e5s",
    "Yakiniku ",
    "Cevapcici",
    "Pasta Alfredo",
    "Sm\u00e5l\u00e4ndska kroppkakor",
    "Snabbaste \u00e4ggr\u00f6ran med cottage cheese",
    "Chili sin carne",
    "\u00c4ggburgare",
    "\u00c4gg- och osttoast",
    "Burrito med b\u00f6nor och kokosris",
    "Pommes Anna",
    "Chicken Kiev - Kyckling Kiev",
    "Chicago hot dog",
    "Banh mi korv - Vietnamesisk korv med br\u00f6d",
    "F\u00e4rsk ravioli med citron- och salviasm\u00f6r",
    "Falafel med vitl\u00f6kss\u00e5s",
    "Potatisbullar med r\u00e5r\u00f6rda lingon ",
    "Parisare ",
    "Viltskavskebab i libabr\u00f6d",
    "Kycklingstroganoff med \u00e4rtris ",
    "Dadel- och chokladglasspinnar",
    "Snabb jordgubbsmjukglass",
    "Gr\u00f6nsakscurry med ris ",
    "Festlig t\u00e5rta ",
    "Sega chokladkakor",
    "Havrepannkakor",
    "Lyxig dalgona coffee",
    "Pancake platter",
    "Pancake cereal - Pannkaksflingor",
    "Dalgona coffee",
    "Spansk aioli utan \u00e4gg",
    "F\u00e4rskpotatis i ugn med brynt sm\u00f6r",
    "Steamed bao buns med chilistekt svamp",
    "R\u00e4kmacka",
    "Banh mi med kyckling",
    "Linsgryta med kokosmj\u00f6lk",
    "Reuben sandwich",
    "Hallonsmoothie med chiafr\u00f6sylt",
    "Mangosmoothie med ingef\u00e4ra",
    "Gr\u00f6n power smoothie",
    "Ceviche med mango och koriander",
    "Kebabs\u00e5s",
    "Kebab i pitabr\u00f6d",
    "Grilled cheese sandwich med Gruy\u00e8re",
    "Grilled cheese sandwich med tv\u00e5 ostar",
    "Grilled cheese sandwich med cheddar",
    "Cherry frutti",
    "Paneerbowl med citronmarinerad zucchini och pistagen\u00f6tter",
    "Quesadillas med paneer,  chorizo och koriander",
    "Enkel paneer tikka masala",
    "Cannelloni med basilika och tomats\u00e5s",
    "Pan pizza med kantareller och dill",
    "Svensk ceviche med ost och marinerade jordgubbar",
    "Snabba ostscones med gr\u00e4ddfil",
    "Ost- och potatisfocaccia med dillfr\u00f6",
    "Salmorejo - Spansk tomatsoppa med cottage cheese ",
    "Gratinerade cottage cheesepl\u00e4ttar med spenat",
    "Torskbiffar med skummig dills\u00e5s - \u00c5rets r\u00e4tt 2020",
    "Vaniljbowl med cottage cheese",
    "Pizza bianco med r\u00f6dbetor och \u00e4delost",
    "Gr\u00e4dds\u00e5s till k\u00f6ttbullar",
    "Chili cheese",
    "\u00c4ppel- och bj\u00f6rnb\u00e4rspaj",
    "Semmelpizza",
    "Ostbollar med cheddar och gr\u00e4sl\u00f6k",
    "Ostbollar med basilka och pinjen\u00f6tter",
    "\u00c4delostbollar med valn\u00f6tscrumble",
    "Sliders med julkryddad Wallenbergare",
    "Kycklinglevermousse med hasseln\u00f6tter och gl\u00f6ggkokt r\u00f6dl\u00f6k",
    "Julskagen med gr\u00f6nk\u00e5l och ros\u00e9peppar",
    "Getostquesadillas med rostade r\u00f6dbetor och valn\u00f6tter",
    "\u00c4delostmousse med kavringskrutonger och f\u00e4rska fikon",
    "Tunnbr\u00f6dsrullar med r\u00f6kt renk\u00f6tt och pepparrot",
    "Nougatmousse med granat\u00e4pple och n\u00f6tter",
    "Kolasnittar med ingef\u00e4ra och vit choklad",
    "Julinkokt lax med ost- och sardellkr\u00e4m",
    "Baconlindade dadlar med \u00e4delost",
    "Pepparkaksfudge med rostad mandel",
    "Sm\u00e5 frestelser med lagrad ost och kn\u00e4ckebr\u00f6d",
    "Sm\u00e5 sm\u00f6rdegspajer med gr\u00e4ddkokt gr\u00f6nk\u00e5l och \u00e4delost",
    "Enkla miniostpajer med stenbitsrom",
    "Blomk\u00e5lsr\u00e5raka med smetana och picklad l\u00f6k",
    "Frasiga skaldjurskroketter",
    "Sojagravad oxfil\u00e9 med sm\u00f6rstekt panko och vitost",
    "Bifftartar med sojasvamp och brynt sm\u00f6rmajonn\u00e4s",
    "Chokladkex med vaniljfyllning",
    "Krustader med svamp, r\u00f6kt gr\u00e4ddfil och cheddarchips ",
    "Bl\u00e5m\u00f6gelostkr\u00e4m med r\u00f6dl\u00f6ksmarmelad och pinjen\u00f6tter",
    "Hummertaco",
    "Blomk\u00e5lskr\u00e4m med \u00e4ppelsallad och hasseln\u00f6tter",
    "Potatistortilla med picklad svamp och saltrostade fr\u00f6n",
    "L\u00f6jromspizza",
    "Laxtartar i noriblad",
    "Tresmaksglass",
    "Chokladkolabar",
    "Blodig Halloweencheesecake",
    "Halloweent\u00e5rta med choklad",
    "L\u00e4skiga halloweenmuffins",
    "Choklad- och apelsinwhoopies",
    "Rostad r\u00f6dbetssallad med gurka och vitost",
    "Grillad sparris och zucchini med vitost",
    "Grillad sallad med avokado och vitost",
    "Julk\u00f6ttbullar med senap och kryddpeppar",
    "Janssons frestelse med jord\u00e4rtskocka",
    "Julgr\u00f6t deluxe",
    "Varm choklad med kanel",
    "Chokladbr\u00e4ck",
    "Mar\u00e4ngkrans med vit chokladkr\u00e4m",
    "Saftig kardemummakaka med jordn\u00f6tstopping",
    "Juliga chokladkakor med kristyr",
    "Vispat brynt sm\u00f6r",
    " Citrus- och r\u00f6dk\u00e5lssallad med valn\u00f6tter och vitost",
    "Gr\u00f6nk\u00e5lspaj med \u00e4delost ",
    "Kron\u00e4rtskocka med kr\u00e4mig sm\u00f6rs\u00e5s och f\u00e4rska tomater",
    "Sm\u00f6rad spetsk\u00e5lsbuljong med gari och friterad brysselk\u00e5l",
    "Purjol\u00f6ksglaserad f\u00e4rskpotatis med forellrom",
    "Amerikanska pl\u00e4ttar med syrad gr\u00e4dde och bj\u00f6rnb\u00e4rssylt",
    "Svamptacos",
    "Kycklinggryta med bacon, \u00e4pple och k\u00e5l",
    "Sm\u00f6rstekt torsk med japansk soja och rostade hasseln\u00f6tter",
    "Viltskavscarbonara med syrad gr\u00e4dde",
    "Svamptoast med bacon och f\u00e4rskost ",
    "Picklad svamp",
    "Salsa p\u00e5 rostade tomater",
    "Lingon- och hasseln\u00f6tsbr\u00f6d",
    "Pizza med chorizo och rostade tomater",
    "Kr\u00e4mig pesto p\u00e5 rostade tomater",
    "Rostade tomater i ugn",
    "Cheesecakekr\u00e4m med svart vinb\u00e4rskompott ",
    "Cheesecakekr\u00e4m med \u00e4ppelkompott",
    "Cheesecakekr\u00e4m med plommonkompott",
    "Rostad auberginesallad med vitost",
    "Gyros i tunnbr\u00f6d med tzatziki",
    "Sommartallrik med lax, potatis och brynt sm\u00f6r",
    "Jalapeno dip",
    "K\u00e5ltacos med portabellosvamp \u2013 \u00c5rets R\u00e4tt 2019",
    "Gr\u00f6nt ramsl\u00f6kssm\u00f6r",
    "\u00c4rtkr\u00e4m",
    "Dukkah med dillfr\u00f6n",
    "\u00c4ppelris",
    "Br\u00f6d utan j\u00e4st",
    "Munkar \u2013 grundrecept",
    "Kallj\u00e4st ostbr\u00f6d",
    "Snabb glass",
    "Vegetarisk lasagne med spenat och linser",
    "Tempura - Japanska frasiga gr\u00f6nsaker",
    "Ostiga quesadillas med b\u00f6nr\u00f6ra",
    "Snabb pizzadeg utan j\u00e4st",
    "Mojo rojo med r\u00f6kt paprika",
    "Mockarutor med kokos",
    "Br\u00f6d med cottage cheese och pumpafr\u00f6n ",
    "Ganache - chokladkr\u00e4m",
    "Frityrsmet till fisk, skaldjur och kyckling",
    "Fransyska i ugn med pressad potatis och gr\u00e4dds\u00e5s",
    "Elotes",
    "Croque Monsieur",
    "Croque Madame",
    "Green goddess dressing",
    "Panzanella med chiliost",
    "Snabb glasst\u00e5rta",
    "Grekisk yoghurt med honung och valn\u00f6tter",
    "Enkel yoghurtdessert med b\u00e4r och krossade kex",
    "Lax i ugn med sparris och gr\u00f6nt sm\u00f6r",
    "Enkel midsommarpavlova",
    "Grillad potatissallad med vitost",
    "Sparris med misosm\u00f6r",
    "Tomatgalette med purjol\u00f6k och ost",
    "Jordgubbar med vit chokladkr\u00e4m",
    "Jordgubbssallad med chili, koriander och linser",
    "Laxbowl med dilldukkah och \u00e4rtkr\u00e4m",
    "Gul \u00e4ggtoddy med mandel och kardemumma",
    "Kyckling i ugn med sparris och rostad vitl\u00f6kskr\u00e4m",
    "P\u00e5skig ris \u00e0 la Malta",
    "Ugnsomelett med bacon, \u00e4delost och r\u00f6dl\u00f6k",
    "Lammstek med tahinikryddad tomats\u00e5s",
    "Citrongr\u00e4dds\u00e5s med timjan ",
    "P\u00e5skpaj med lammf\u00e4rs och getost",
    "Krispig ostpaj med sparris och citron",
    "P\u00e5sksallad",
    "Burrito med kyckling",
    "Penne med svamp och pinjen\u00f6tter",
    "Citronkyckling med stuvad spetsk\u00e5l",
    "H\u00f6grevsgryta med chiliostkr\u00e4m",
    "Lyxig ostpaj",
    "Sill med kryddost",
    "Kr\u00e4ftskagen med kryddost ",
    "H\u00f6grevsburgare med chili och f\u00e4nk\u00e5lsslaw",
    "Viltf\u00e4rsbiffar med rostade rotfrukter",
    "Stekt lax med potatisstomp",
    "Avokadomacka med cottage cheese",
    "Vegogryta med svamp",
    "Kornotto med butternutpumpa och ljummen tryffelvin\u00e4grett",
    "Rimmad torskrygg med bl\u00e5mussels\u00e5s och jord\u00e4rtskocka",
    "Mandelkaka med r\u00e5r\u00f6rda hjortron och vispad vaniljkr\u00e4m",
    "Oxfil\u00e9 med srirachaglaze, \u00e4delost och gr\u00e4ddstuvad rotselleri",
    "Skaldjursbisque med hummer och picklad gurka",
    "Kr\u00e4mig gr\u00f6t med \u00e4pple och fr\u00f6karamell ",
    "B\u00e4rsmoothie med ingef\u00e4ra och r\u00f6dbeta",
    "Chokladpannkakor med kardemummayoghurt",
    "Chokladsmoothie med avokado och hallon",
    "Mac and cheese med r\u00f6dbetor, spenat och citron",
    "Mild \u00e4delostdressing",
    "Enkel pizza med mild \u00e4delost, potatis och fikon",
    "Taco med paneer och raita",
    "Rostad majssallad med kryddstekt paneer och limedressing",
    "Paneer tikka masala med naanbr\u00f6d",
    "Nudelwok med paneer, shiitake och koriander",
    "Paneer Stroganoff",
    "L\u00f6vbiff med \u00e4delost",
    "Fl\u00e4skfil\u00e9 med \u00e4delost",
    "Sloppy Joes med \u00e4delost",
    "Glutenfri pajdeg",
    "\u00c4delosts\u00e5s",
    "Pannkaka",
    "Kladdkaka",
    "Lasagne",
    "Chokladbollar",
    "K\u00e4rleksmums",
    "Kanelbullar",
    "V\u00e5fflor",
    "Pasta carbonara",
    "Rabarberpaj med smuldeg",
    "Kladdig kladdkaka",
    "Smulpaj \u2013 grundrecept",
    "Tacopaj",
    "Kn\u00e4ck \u2013 grundrecept",
    "Muffins",
    "Stuvade makaroner",
    "K\u00f6ttf\u00e4rss\u00e5s",
    "K\u00f6ttbullar",
    "Chocochock muggkaka",
    "Sockerkaka",
    "Banankaka",
    "K\u00f6ttf\u00e4rslimpa",
    "Brownie \u2013 grundrecept",
    "V\u00e4sterbottenpaj",
    "Lussekatter",
    "Kycklingpaj",
    "Bechamels\u00e5s",
    "Fattiga riddare \u2013 grundrecept",
    "Bruns\u00e5s \u2013 grundrecept",
    "Amerikanska pannkakor \u2013 grundrecept",
    "Havresmulpaj",
    "Chokladmousse",
    "K\u00e5lpudding \u2013 grundrecept",
    "Fl\u00e4skpannkaka med stekt \u00e4pple",
    "Lussebullar \u2013 grundrecept",
    "Mar\u00e4nger",
    "Scones \u2013 grundrecept",
    "Gr\u00f6n \u00e4rtsoppa",
    "Kyckling med parmaskinka och balsams\u00e5s",
    "Tjockpannkaka",
    "Frasv\u00e5fflor",
    "Kolakakor",
    "Hamburgare ",
    "Picklad r\u00f6dl\u00f6k",
    "Enkel choklads\u00e5s",
    "Broccolipaj med purjol\u00f6k",
    "M\u00f6rdegskakor",
    "Porterstek",
    "Pannkakssmet",
    "Pinocchiot\u00e5rta",
    "Blomk\u00e5lssoppa",
    "Silviakaka",
    "Spenatsoppa",
    "Kokostoppar",
    "Vit chokladmousse",
    "Klassisk kn\u00e4ck",
    "Janssons frestelse \u2013 grundrecept",
    "Moussaka \u2013 grundrecept",
    "Enkel spaghetti carbonara",
    "Pannbiff",
    "Coleslaw \u2013 grundrecept",
    "Boeuf bourguignon",
    "Fl\u00e4skfil\u00e9gryta med ost- och senapss\u00e5s",
    "Busenkel Bearnaises\u00e5s",
    "Chocolate chip cookies",
    "Vegetarisk lasagne",
    "Italiensk kycklingpasta",
    "Potatis- och purjol\u00f6kssoppa",
    "Grekisk sallad",
    "Kokt torsk med \u00e4ggs\u00e5s",
    "Falafel \u2013 grundrecept",
    "Syltkakor",
    "Pepparkaksdeg",
    "Toast skagen",
    "Byg\u00e5rdens k\u00f6ttgryta",
    "Frozen cheesecake",
    "Saffransbullar med mandelmassa",
    "Smulpaj med \u00e4pple",
    "K\u00f6ttf\u00e4rspaj",
    "Plankstek",
    "Kr\u00e4mig potatis- och purjol\u00f6kssoppa",
    "Jordn\u00f6tss\u00e5s",
    "Korv Stroganoff",
    "Havregrynsgr\u00f6t",
    "Chicken Tikka Masala",
    "Citronkyckling med oliver",
    "Gratinerad k\u00f6ttf\u00e4rspasta",
    "Pad thai",
    "Ugnsbakad torskrygg med pepparrotskr\u00e4m",
    "Risgrynsgr\u00f6t",
    "Fransk kycklinggryta",
    "Overnight oats",
    "Lax i folie",
    "Tigerkaka",
    "Griljerad julskinka",
    "Pajdeg \u2013 grundrecept",
    "Lax i ugn med spenat och citrons\u00e5s",
    "Kalops \u2013 grundrecept",
    "Raggmunk med fl\u00e4sk",
    "Baconlindad kycklingfil\u00e9",
    "Chokladsnittar",
    "Cheesecake \u2013 grundrecept",
    "Ugnsstekt laxsida",
    "Potatisgrat\u00e4ng",
    "Tsatsiki",
    "Kantarells\u00e5s",
    "Snabb biff Stroganoff",
    "Hasselbackspotatis",
    "Br\u00e4nda mandlar",
    "Kantarellsoppa",
    "Macaroni and cheese",
    "Kn\u00e4ckig rabarberpaj",
    "Pulled Beef",
    "Pulled pork \u2013 grundrecept",
    "Chokladfondant",
    "Citroncheesecake",
    "Rabarberkr\u00e4m",
    "Gratinerad hummer med citron och vitl\u00f6k",
    "R\u00f6dbetsbiffar",
    "K\u00f6ttf\u00e4rsgrat\u00e4ng",
    "Pizzadeg \u2013 grundrecept",
    "Enkel ostkaka",
    "Sm\u00f6rdeg \u2013 grundrecept",
    "K\u00f6ttf\u00e4rsbiffar i timjans\u00e5s",
    "Fiskgryta med saffran",
    "Glutenfri kladdkaka",
    "Broccolisoppa",
    "Stuvad spenat",
    "Pannacotta \u2013 grundrecept",
    "Kycklinggryta",
    "\u00c4ggtoddy",
    "Paneer masala",
    "S\u00f6tpotatis pommes frites",
    "Lyxig sm\u00f6rg\u00e5st\u00e5rta med r\u00e4kor och lax",
    "Guacamole \u2013 grundrecept",
    "Trattkantarellsoppa",
    "Pavlova med lemoncurd",
    "Pulled chicken",
    "Laxpasta med lime",
    "One pot pasta med b\u00f6nor och soltorkade tomater",
    "Laxpaj med spenat",
    "Amerikansk pumpapaj",
    "Filmj\u00f6lksbr\u00f6d",
    "Flygande Jakob \u2013 grundrecept",
    "Enchiladas med kyckling",
    "Kr\u00e4mig pastagrat\u00e4ng med skinka",
    "Jord\u00e4rtskockssoppa",
    "Halloumi Stroganoff",
    "R\u00e4kcocktail",
    "Bakad potatis",
    "Kycklingsoppa med stil",
    "H\u00f6grevsgryta med syrad gr\u00e4dde och sambal",
    "Vitl\u00f6kssm\u00f6r",
    "Sk\u00e5nsk \u00e4ggakaka",
    "Semlor",
    "Grundrecept potatismos",
    "Smulpaj med hallon och bl\u00e5b\u00e4r",
    "Risotto \u2013 grundrecept",
    "Chiapudding",
    "Ostpaj",
    "Bouillabaisse \u2013 grundrecept",
    "Helstekt kyckling med \u00f6rter",
    "Krabbelurer",
    "Fudge \u2013 grundrecept",
    "Mjuk pepparkaka",
    "Snabb och mustig kycklinggryta",
    "Kycklingpasta med spenat och parmesan",
    "Kycklingfil\u00e9 med dijonsenap och gr\u00e4sl\u00f6k",
    "Kr\u00e4mig gubbr\u00f6ra med matjessill",
    "Ryttarkaka",
    "Limekyckling",
    "Chokladmuffins med frosting",
    "Pasta med italiensk kyckling",
    "Spaghetti med k\u00f6ttf\u00e4rss\u00e5s",
    "Sticky buns med saffran",
    "Donuts",
    "F\u00e4rgglad gr\u00f6nsakspaj",
    "Morotssoppa med ingef\u00e4ra",
    "Hallongrottor",
    "Tacograt\u00e4ng",
    "Omelett \u2013 grundrecept",
    "Paprika- och chilikyckling",
    "Ris \u00e0 la Malta \u2013 grundrecept",
    "Julk\u00f6ttbullar med kryddpeppar",
    "Ost- och skinkpaj",
    "Laxt\u00e5rta med l\u00f6jrom",
    "K\u00f6ttbullar i ugn",
    "Rabarberkaka i l\u00e5ngpanna",
    "Gr\u00f6nk\u00e5lspaj",
    "Gulaschsoppa",
    "Falukorv i ugn",
    "Caesarsallad",
    "Pytt i panna",
    "Pasta med laxs\u00e5s och r\u00e4kor",
    "Kasslergrat\u00e4ng",
    "Broccoligrat\u00e4ng med pasta",
    "Macarons \u2013 grundrecept",
    "Enchiladas \u2013 grundrecept",
    "Wallenbergare \u2013 grundrecept",
    "Torskrygg med pocherat \u00e4gg och vitvinss\u00e5s",
    "K\u00f6ttf\u00e4rspiroger",
    "K\u00f6ttf\u00e4rsbiffar med pepprig s\u00e5s",
    "Cake pops \u2013 grundrecept",
    "Vinaigrette",
    "Frosting",
    "Sweet chilis\u00e5s",
    "Bananpannkakor \u2013\u00a0grundrecept",
    "Timjankyckling med fransk senap",
    "Gr\u00e4ddig pasta",
    "Gr\u00f6nk\u00e5lssoppa",
    "Vaniljbullar",
    "Chili con carne med gr\u00f6nsaker",
    "Bl\u00e5b\u00e4rspaj",
    "Tunn och frasig ugnspannkaka",
    "Morotskaka",
    "Citronmar\u00e4ngpaj",
    "Smulpaj med jordgubbar",
    "Ugnsbakad kyckling med rotfrukter och currys\u00e5s",
    "Marinerad fl\u00e4skfil\u00e9",
    "Sparrissoppa",
    "Saffranscheesecake",
    "Dragonkyckling",
    "Pinnbr\u00f6d",
    "Skagentoast",
    "R\u00f6dvinss\u00e5s",
    "L\u00e4tt k\u00f6ttgryta",
    "Spaghetti med kr\u00e4mig pesto",
    "Klassisk bolognese",
    "Kr\u00e4miga burritos",
    "Pastasallad med ost",
    "Enkel potatissallad",
    "Hollandaises\u00e5s \u2013 grundrecept",
    "L\u00e5ngk\u00e5l",
    "Medelhavspaj",
    "Pasta med kr\u00e4mig svamps\u00e5s och halloumi",
    "Pasta carbonara med syrad gr\u00e4dde",
    "Havreflarn \u2013 grundrecept",
    "Fl\u00e4skfil\u00e9 med lingons\u00e5s",
    "Fish tacos",
    "Tomatsoppa",
    "Biff Stroganoff med syrad gr\u00e4dde",
    "Kycklingfil\u00e9 med dragonpotatis och bearnaises\u00e5s",
    "Dillstuvad potatis",
    "Vinb\u00e4rssaft",
    "Fl\u00e4skfil\u00e9 med s\u00e5s och ugnsstekta gr\u00f6nsaker",
    "Gravad laxpasta",
    "Fylld l\u00f6vbiff",
    "T\u00e5rtbotten",
    "Kr\u00e4mig laxlasagne med spenat",
    "Bamsebiff",
    "Chokladt\u00e5rtbotten",
    "Tortilla med k\u00f6ttf\u00e4rs",
    "Lasagne pronto",
    "Lammstek i ugn",
    "Pasta med ost- och champinjons\u00e5s",
    "R\u00e5r\u00f6rd vaniljs\u00e5s",
    "Paella \u2013 grundrecept",
    "Mar\u00e4ngt\u00e5rta med citron",
    "Grekisk tsatsiki",
    "Klassisk k\u00f6ttf\u00e4rslimpa med kr\u00e4mig gr\u00e4dds\u00e5s och pressgurka",
    "Kladdkakemuffins",
    "Fransk omelett med champinjoner",
    "Auberginegryta",
    "L\u00e5gtempererad rostbiff med tomater",
    "Linssoppa",
    "Kik\u00e4rtsbiffar med morotstsatsiki",
    "Currys\u00e5s",
    "Kr\u00e4mig pasta med kyckling, svamp och broccoli",
    "Remoulads\u00e5s \u2013 grundrecept",
    "Kyckling i jordn\u00f6tss\u00e5s",
    "Falafel med myntadressing",
    "Key Lime pie",
    "Tzatziki \u2013 grundrecept",
    "Biff teriyaki",
    "Kycklinggryta med sparris",
    "Fisksoppa",
    "Busenkla korvgrytan",
    "GI-lasagne",
    "Tomtefudge ",
    "Kycklinggryta med \u00e4delost",
    "Cheesecake i glas",
    "Havrekakor",
    "Pepparkakor \u2013 grundrecept",
    "Tacopaj med kyckling",
    "Smoothie med jordgubb",
    "Smuldeg",
    "Sillt\u00e5rta",
    "Kokt torsk med brynt sm\u00f6r",
    "Korvpanna i italiensk s\u00e5s",
    "Saftig sockerkaka",
    "Rabarbersaft",
    "S\u00f6tpotatissoppa med lime",
    "Vit chokladmousset\u00e5rta med passionsfrukt ",
    "Sallad med r\u00f6dbetor, hallon och brynt limesm\u00f6r",
    "Glutenfri v\u00e4sterbottenpaj",
    "Rocky road \u2013 grundrecept",
    "Svampsoppa",
    "No bake cheesecake i glas",
    "Rullt\u00e5rta \u2013 grundrecept",
    "Lammstek med ben",
    "Snickerskaka",
    "Snabb lasagne",
    "Vispat brynt sm\u00f6r med matjessill",
    "Broccolipaj med \u00e4delost",
    "Hallonpaj",
    "Tomatpasta med halloumi och avokado",
    "Ostpaj med Svecia",
    "Limes\u00e5s",
    "Oxfil\u00e9 med peppars\u00e5s och ugnsrostad potatis",
    "Cheesecake med vit choklad",
    "Enchiladas med kycklingr\u00f6ra",
    "Vitl\u00f6ksfr\u00e4sta chilir\u00e4kor",
    "Cookies \u2013 grundrecept",
    "Gr\u00f6nsaksgrat\u00e4ng",
    "Petit choux - grundrecept",
    "R\u00e4ksallad med Rhode Island",
    "Blomk\u00e5lsmos",
    "Broccoligrat\u00e4ng med ost och sm\u00e5tomater",
    "Skaldjurspaj",
    "Pasta med strimlad biff",
    "Spaghetti med linss\u00e5s och broccolisallad",
    "Kolakaka med saffran",
    "Fiskgrat\u00e4ng med purjol\u00f6k, morot och f\u00e4nk\u00e5l",
    "Vegetarisk snabblasagne",
    "Svamps\u00e5s",
    "Lyxig gr\u00e4ddt\u00e5rta",
    "Makaronipudding",
    "L\u00e4tt svamppasta",
    "Brynt sm\u00f6r",
    "Hamburgare p\u00e5 h\u00f6grev ",
    "Snabb laxs\u00e5s",
    "Getostpaj med r\u00f6dbetor",
    "Blomk\u00e5lsris",
    "Kycklingsoppa med nudlar",
    "Helstekt fl\u00e4skfil\u00e9 med chilis\u00e5s",
    "Ugnsstekt lax med rostade rotfrukter",
    "Torsk i ugn med rotfrukter",
    "Mangosalsa med koriander",
    "Enkel chokladmousse",
    "Aladdins dr\u00f6mkaka",
    "Peppars\u00e5s",
    "Beef chili",
    "Snabb korvgryta",
    "Hallonsmoothie med cottage cheese",
    "Grundrecept p\u00e5 kr\u00e4mig gubbr\u00f6ra",
    "B\u00f6nstroganoff",
    "Toscapaj med \u00e4pple",
    "Fullkornspasta med osts\u00e5s",
    "Granola \u2013 grundrecept",
    "Fina fiskgrytan",
    "Focaccia \u2013 grundrecept",
    "Biscotti \u2013 grundrecept",
    "Hallonmuffins",
    "Chunky tomats\u00e5s med linser",
    "Lasagne med morot och cottage cheese",
    "Bondens \u00e4ppelkaka",
    "Inbakad oxfil\u00e9",
    "Kantarellstuvning",
    "Tryffel med karamelliserad mj\u00f6lk",
    "Rabarber- och jordgubbspaj",
    "Pl\u00e4ttar med cottage cheese",
    "Amerikanska pannkakor med frukt och b\u00e4r",
    "Citron och limekaka",
    "Viltgryta",
    "Gr\u00f6npeppars\u00e5s",
    "Karamellpopcorn",
    "Budapestrulle",
    "Lax med saffran",
    "Svamplasagne",
    "\u00c4lgf\u00e4rsbiffar",
    "Sk\u00e4rg\u00e5rdssill",
    "Citronfromage",
    "Pasta supergreen",
    "Skirat sm\u00f6r",
    "F\u00e4rskpotatissallad",
    "Chokladt\u00e5rta med tryffel",
    "Snabb pastasoppa",
    "Brownies",
    "Ischoklad",
    "Fettsn\u00e5l kladdkaka med lime",
    "Lyxiga kanelbullar",
    "Gr\u00f6nk\u00e5lschips",
    "Ugnsbakad lax med enkel potatissallad",
    "Gr\u00f6nk\u00e5lspaj med kvarg",
    "Sl\u00e4ta lussebullar med socker",
    "Pasta med osts\u00e5s och svamp",
    "Chokladsemla de luxe",
    "Paprikas\u00e5s",
    "P\u00e5skpaj",
    "Islatte",
    "Fl\u00e4skytterfil\u00e9 i peppars\u00e5s",
    "Grekisk paj med ost och gr\u00f6nsaker",
    "Bakad torsk med sm\u00f6rs\u00e5s",
    "Mj\u00f6lkchokladmousse med browniesmulor och hallon",
    "Lasagne i l\u00e5ngpanna",
    "Bulgur med lax och limedressing",
    "Smoothie med hallon och kokos",
    "Sl\u00e4ta bullar",
    "Halloncheesecake i glas",
    "H\u00f6stgryta med svamp och \u00e4pple",
    "Marockansk kycklinggryta med pitabr\u00f6d",
    "Kr\u00e4mig jord\u00e4rtskockssoppa",
    "Lax med citrons\u00e5s",
    "Vegetarisk gulasch",
    "Fl\u00e4skl\u00e4gg med rotmos",
    "\u00c4rtsoppa med rimmat fl\u00e4sk",
    "S\u00f6tpotatisklyftor med baconr\u00f6ra",
    "Kr\u00e4ftpasta",
    "Dal Makhani",
    "Citrontarte med honung",
    "Citronmuffins",
    "Vegetarisk pasta med gr\u00f6nk\u00e5l, ost och fr\u00f6n",
    "Gravad lax \u2013 steg f\u00f6r steg",
    "Vaniljpannacotta",
    "Enchiladas med kyckling och cottage cheese",
    "Browniet\u00e5rta med bl\u00e5b\u00e4rsmousse",
    "F\u00e4rsbiffar med vitost",
    "Godaste julkolan",
    "Laxpudding",
    "Kycklinggryta med rostade rotfrukter",
    "Vegetarisk moussaka med aubergine och citron",
    "Lemon curd",
    "Svamp- och purjol\u00f6kspaj",
    "Chokladkola",
    "Heta r\u00e4kor med ris",
    "Citron- och r\u00e4ks\u00e5s till pasta",
    "Laxsoppa med spenat",
    "\u00c4ngasoppa",
    "Omelett med ost och skinka",
    "Helgrillad blomk\u00e5l med rivet ost- och gr\u00e4sl\u00f6kssm\u00f6r",
    "Bakad torskrygg med vitvinss\u00e5s och gr\u00e4sl\u00f6ksolja",
    "Svenska pepparkakor",
    "Apfelstrudel",
    "Pepparkakscheesecake",
    "Mandelmusslor - grundrecept",
    "Arlas kanelbulle",
    "\u00c4ggwrap med r\u00f6kt lax",
    "Ugnsrostade gr\u00f6nsaker",
    "Rullt\u00e5rta med b\u00e4r",
    "Mammas chokladfudge",
    "Inbakad fl\u00e4skfil\u00e9",
    "Kr\u00e4mig r\u00e4kpasta",
    "Kanel- och kardemummabullar",
    "Minipajer med ost",
    "Rotmos",
    "Fl\u00e4skytterfil\u00e9 i ugn med oliver",
    "Ljummen potatissallad",
    "Omelett med avokado",
    "Indisk linssoppa",
    "Bibimbap",
    "Cannelloni med zucchini och valn\u00f6tter",
    "Renskavsgryta",
    "Gaffelkakor",
    "Revbensspj\u00e4ll med honungsglaze",
    "Pastagrat\u00e4ng med kassler",
    "Smoothie med hallon",
    "Kall bearnaises\u00e5s",
    "Varm choklad med vispgr\u00e4dde",
    "Cr\u00eapes med svamp och l\u00f6kfyllning",
    "Sockerkaka utan \u00e4gg",
    "Gr\u00e4dds\u00e5s",
    "Lyxig \u00e4ggr\u00f6ra",
    "Varmr\u00f6kt lax med gr\u00e4sl\u00f6kss\u00e5s",
    "R\u00f6dvinssky",
    "Pizzabullar",
    "Rucolapaj med tomater",
    "Klassisk chokladtryffel",
    "Sm\u00f6rdegsinbakad sparris",
    "Ugnsstekta kycklingvingar",
    "Kycklinggrat\u00e4ng med cashewn\u00f6tter",
    "Hallont\u00e5rta",
    "Snabb biffgryta med gr\u00f6npeppar",
    "Milkshake med hallon",
    "Pumpasoppa",
    "Djungelgryta",
    "Blomk\u00e5lsgrat\u00e4ng",
    "Kycklingpasta",
    "Bearnaises\u00e5s \u2013 grundrecept",
    "Clotted cream",
    "Engelska miniscones",
    "Senapssill",
    "\u00d6rtstekt fl\u00e4skkarr\u00e9",
    "Mustig fl\u00e4skfil\u00e9panna",
    "Hallonmousse",
    "Smoothie med mango och banan",
    "Ratatouille \u2013 grundrecept",
    "Chokladmousset\u00e5rta",
    "Brysselkex",
    "Pepparrotsk\u00f6tt",
    "K\u00f6ttf\u00e4rss\u00e5s p\u00e5 minuten",
    "Asiatiska kycklingspett",
    "Fisksoppa med f\u00e4nk\u00e5l och saffran",
    "Mustig chiligryta",
    "Kolatryffelpaj med flingsalt",
    "Fl\u00e4dersaft",
    "Sockerlag",
    "R\u00e5r\u00f6rda lingon",
    "Dr\u00f6mmar \u2013 grundrecept",
    "Bananbr\u00f6d",
    "Lammstek med varmt \u00f6rtsm\u00f6r",
    "Pasta italiano",
    "Tomat- och pastasoppa",
    "Kn\u00e4ck i mikron",
    "Lax i ugn med kr\u00e4mig penne, spenat och chili",
    "Chefs burger med karamelliserad l\u00f6k",
    "T\u00e5rta med hallonbavaroise och chokladganache",
    "Italiensk kycklingsoppa",
    "Baba ganoush \u2013 grundrecept",
    "Oxfil\u00e9 provencale",
    "Kn\u00e4ckbr\u00e4ck",
    "Midsommart\u00e5rta",
    "Vaniljhj\u00e4rtan",
    "Mandelmassa \u2013 grundrecept",
    "Fl\u00e4skfil\u00e9 balsamico",
    "Bakad potatis f\u00f6r hela familjen",
    "Cannelloni med vitost och spenat",
    "H\u00f6grevsburgare med bacon och cheddar",
    "Kn\u00e4ckig kladdkaka",
    "B\u00e4rt\u00e5rta",
    "Rostad paprikasoppa",
    "Lazy dinner - kyckling i ugn med gr\u00f6nsaker",
    "Kycklingbullar i curryjordn\u00f6tss\u00e5s",
    "Lyxig lakritskola",
    "Gammaldags saffransbr\u00f6d",
    "Potatis- och purjol\u00f6kssoppa med kyckling",
    "Citronfisk med timjan",
    "Hummus \u2013 grundrecept",
    "Fruktig dessert i glas",
    "Pankostekt kyckling med citron ",
    "Kantarellpaj",
    "Pulled pork i lergryta",
    "\u00c4ppelmos",
    "Gravlaxtartar",
    "Sloppy Joe burger",
    "Bountybollar",
    "Mar\u00e4ngt\u00e5rta med rabarber och jordgubbar",
    "Hallonkolamilkshake",
    "Prinsesst\u00e5rta \u2013 grundrecept",
    "Gratinerad blomk\u00e5l med bacon, tomat och svamp",
    "Oxfil\u00e9 med madeiras\u00e5s ",
    "Klassiska schackrutor",
    "Tacopaj med s\u00f6tpotatis och gr\u00f6nsaker",
    "Matjessillt\u00e5rta",
    "Crostini med lufttorkad skinka",
    "Rostad het pumpasoppa",
    "Roms\u00e5s \u2013 grundrecept",
    "Fransk l\u00f6ksoppa",
    "Klassisk sommarkyckling",
    "Entrec\u00f4te med bearnaise och medelhavspotatissallad",
    "No bake cheesecake",
    "Grillad entrecote med medelhavssm\u00f6r",
    "Kn\u00e4ckig \u00e4ppelpaj",
    "Glutenfri kladdkaka med dulce de leche",
    "Langos \u2013 grundrecept",
    "Muggkaka med bl\u00e5b\u00e4r och kanel",
    "Kolasnittar",
    "Vegetariska fajitas med cottage cheese",
    "Cheeseburgare ",
    "Skinkpasta med svamp",
    "Quinoasallad med kyckling",
    "Sm\u00f6rkr\u00e4m",
    "Dills\u00e5s",
    "Kycklingsallad \u00e0 la Gustav",
    "Chokladkolasnitt",
    "Kassler i ugn med persilja",
    "Pannacotta med b\u00e4r",
    "Finska pinnar",
    "Nasi Goreng \u2013 grundrecept",
    "Tagliatelle med fl\u00e4skfil\u00e9 och citron",
    "Tomatbruschetta",
    "Sandwiches med olika fyllning",
    "Tonfisksallad",
    "Ugnsomelett med svampfyllning",
    "Jordgubbssylt",
    "Dr\u00f6mrullt\u00e5rta",
    "Enkel k\u00f6ttf\u00e4rss\u00e5s ",
    "Mazariner",
    "Barnens chokladbollar",
    "Rabarberkyckling",
    "Pajdeg med \u00e4gg",
    "\u00c4ppelkaka",
    "\u00c4ngamat",
    "Potatismos",
    "Dj\u00e4vuls\u00e4gg",
    "Ankbr\u00f6st med gr\u00f6npeppars\u00e5s",
    "Paj med Svecia",
    "Club sandwich \u2013 grundrecept",
    "Kr\u00e4mig korv Stroganoff",
    "Krustader med avokado, r\u00e4kor och pepparrot",
    "Red velvet cake",
    "Kyckling Stroganoff",
    "Sm\u00f6rdegspizza med spenat och picklad r\u00f6dl\u00f6k",
    "Sparrispaj",
    "Pestopaj",
    "Samosas",
    "Pavlova \u2013 grundrecept",
    "Korv stroganoff med potatismos",
    "Sandras skogspanna",
    "Vit chokladtryffel med lime",
    "Gr\u00e4ddkola med choklad och flingsalt",
    "Nyttiga chokladbollar",
    "Proteinsmoothie",
    "Jordgubbst\u00e5rta",
    "Sk\u00e4rg\u00e5rdssoppa med r\u00e4kor och purjol\u00f6k",
    "Asiatisk nudelsallad med r\u00e4kor",
    "\u00d6rtcr\u00e8me",
    "Mjuk pepparkaka med frosting och n\u00f6tter",
    "Texmex cowboysoppa",
    "Lobster roll",
    "Dijonnaise",
    "Saffranskladdkaka med hallongr\u00e4dde",
    "Skarps\u00e5s",
    "Inlagd sill p\u00e5 klassiskt vis",
    "Dj\u00e4vulskyckling",
    "Helbakad rotselleri med sm\u00f6rs\u00e5s",
    "Trifle p\u00e5 \u00e4pple med smulkrisp och vaniljglass",
    "Fransk laxl\u00e5da",
    "Marockansk k\u00f6ttgryta med granat\u00e4pple",
    "Ravioli med spenat och ricotta samt citronsm\u00f6r",
    "Pajdeg med kvarg",
    "Italiensk pastapanna med salsiccia",
    "Fl\u00e4skfil\u00e9panna",
    "Vegetarisk curry",
    "Fylld portabello med \u00f6rtig b\u00f6nr\u00f6ra",
    "Fruktig b\u00f6nsallad med fetaost och n\u00f6tter ",
    "Kycklinggryta med svamps\u00e5s",
    "Overnight oats med r\u00e5r\u00f6rda hallon och mandel",
    "Bavaroise",
    "Paj med varmr\u00f6kt lax",
    "Indisk kik\u00e4rtsgryta",
    "Nudelsoppa",
    "Kallj\u00e4sta kanelbullar",
    "Skinksnurror",
    "Engelska scones",
    "\u00c4ppelpizza med kolas\u00e5s",
    "Bananmilkshake",
    "Vaniljparfait",
    "Gr\u00e4ddfilss\u00e5s med \u00f6rter",
    "\u00c4ppelkaka i l\u00e5ngpanna",
    "P\u00e5skmuffins",
    "Kycklingschnitzel med stomp",
    "Panna med vitk\u00e5l och champinjoner",
    "Krusb\u00e4rsmarmelad",
    "Korv Stroganoff med basilikasmak",
    "Fiskgryta",
    "Pasta med rostad vitl\u00f6k och karljohan cr\u00e8me fraiche",
    "Minifrittata",
    "Lyxig sockerkaka",
    "Kladdkaka med brynt sm\u00f6r och flingsalt",
    "Bregottkakor",
    "Citronrutor",
    "Dillk\u00f6tt",
    "Banoffee-t\u00e5rta",
    "Morotskaka i l\u00e5ngpanna",
    "Citronkyckling med potatismos",
    "Kreolsk gryta",
    "Fetaostsallad",
    "Toscakaka \u2013 grundrecept",
    "Kristyr \u2013 grundrecept",
    "Hallonsemifreddo med daim",
    "Biff i het s\u00e5s",
    "Biffgryta med chili och choklad",
    "Rosenbr\u00f6d",
    "Gubbr\u00f6ra med lax",
    "Kik\u00e4rtspilaff",
    "Hallon- och bl\u00e5b\u00e4rssmoothie",
    "Brantevikssill",
    "Kr\u00e4fttoast",
    "Snabb thaisoppa med kyckling",
    "R\u00e4kpasta med hummerfond",
    "Rabarber- och hallonpaj med vit choklad ",
    "Torsk med \u00e4ggs\u00e5s",
    "Sj\u00f6r\u00f6varfisk",
    "R\u00f6dk\u00e5l",
    "Mimosasallad",
    "Fransk fisksoppa",
    "B\u00f6nbiffar i pitabr\u00f6d",
    "Grundrecept gryta",
    "S\u00b4mores tartlett",
    "Snickersrutor",
    "Italiensk mandelfisk",
    "Pastasallad med lax",
    "Melonsallad med vitost ",
    "Hemmagjord daim ",
    "Minichokladmuffins",
    "Auberginer i ugn",
    "Ost- och skinksallad ",
    "K\u00f6ttf\u00e4rs Bombay med jordn\u00f6tter",
    "Kladdkaka med chokladkr\u00e4m",
    "Mango chicken balti",
    "Tunnbr\u00f6d i stekpanna",
    "Kokospannkaka",
    "Helstekt oxfil\u00e9 med bakade kvisttomater",
    "Wok med biff och asiatisk s\u00e5s",
    "Kycklingtacos",
    "Klassisk vaniljs\u00e5s",
    "Rosmarinkyckling med bacon",
    "Gryta med quorn",
    "Kycklingsallad med apelsin och n\u00f6tter",
    "Randig chokladterrin, rostad krisp och vaniljkr\u00e4m ",
    "Citronlax",
    "Grekisk kyckling",
    "Mango cheesecake",
    "Vitvinss\u00e5s",
    "Stuvad gr\u00f6nk\u00e5l med citron och cr\u00e8me fraiche",
    "Vegetarisk pasta med pesto",
    "Italiensk soppa med farro",
    "Frozen cheesecake med mango och passionsfrukt",
    "Potatissoppa",
    "Franska fiskbiffar",
    "Chokladdoppad hallonkola",
    "Thaisoppa med kyckling och glasnudlar",
    "Toscansk hummersoppa",
    "Potatissallad",
    "Kyckling masala med chili och yoghurt",
    "Pasta med ost- och citrons\u00e5s",
    "Gravlaxs\u00e5s",
    "Korv- och potatisgrat\u00e4ng",
    "Fl\u00e4derparfait",
    "Pankobakad torsk med krossad potatis och kall citrons\u00e5s",
    "Apelsinkyckling med chili",
    "Coq au vin",
    "V\u00e5rrullar \u2013 grundrecept",
    "Scrambled eggs med cottage cheese",
    "Fl\u00e4skfil\u00e9panna med smak av svamp",
    "Paj med prim\u00f6rer och rostade pinjen\u00f6tter",
    "Empanadas",
    "Hallonsmoothie med kvarg",
    "Cannelloni med kyckling och svamp",
    "Toscansk soppa med kyckling",
    "Limecheesecake med jordgubbstopping",
    "Tortellini med osts\u00e5s",
    "Fiskgrat\u00e4ng",
    "Tortillastubbar",
    "Glasst\u00e5rta med citrongr\u00e4s och bl\u00e5b\u00e4r p\u00e5 biskvibotten",
    "Kladdkaka i l\u00e5ngpanna med kolakvarg",
    "Kr\u00e4ftsoppa",
    "Pasta med lax",
    "Vaniljglass",
    "Mazarinkaka med hallonglasyr",
    "Lakritskn\u00e4ck",
    "Cr\u00e8me brul\u00e9e med r\u00e5r\u00f6rda jorgubbar",
    "Wienerbr\u00f6d",
    "Bondkakor",
    "Chicken \u00e1 la King",
    "Basilikafisk med citrons\u00e5s",
    "Kantarellsoppa med gr\u00f6nk\u00e5lschips",
    "Julmustkyckling",
    "N\u00f6tf\u00e4rsbiffar med franska \u00f6rter",
    "Asiatisk lax",
    "Chokladkaka med kolasmet och marmorerad topping",
    "Indiska k\u00f6ttbullar",
    "Minipajer med kantareller",
    "Kycklingklubbor med kr\u00e4mig avokador\u00f6ra",
    "Bibimbap med tofu",
    "Bananmuffins",
    "Helgrillad lammentrecote med vitl\u00f6kssparris",
    "Lax med pesto",
    "Saffranskaka i l\u00e5ngpanna",
    "Crostini med p\u00e4ron och honungsrostade valn\u00f6tter",
    "Chokladrullt\u00e5rta",
    "Matig ugnspannkaka med potatis",
    "Dubbelbakad potatis med bacon och ost",
    "Minipajer med \u00e4delost",
    "Pasta med gr\u00f6nk\u00e5l och rostad mandel",
];

export { dummyNames };
